package nextmethod.net;

/**
 *
 */
public enum HttpStatusCode {

	Continue,
	SwitchingProtocols,
	Ok,
	Created,
	Accepted,
	NonAuthoritativeInformation,
	NoContent,
	ResetContent,
	PartialContent,
	MultipleChoices,
	Ambiguous,
	MovedPermanently,
	Moved,
	Found,
	Redirect,
	SeeOther,
	RedirectMethod,
	NotModified,
	UseProxy,
	Unused,
	TemporaryRedirect,
	RedirectKeyVerb,
	BadRequest,
	Unauthorized,
	PaymentRequired,
	Forbidden,
	NotFound,
	MethodNotAllowed,
	NotAcceptable,
	ProxyAuthenticationRequest,
	RequestTimeout,
	Conflict,
	Gone,
	LengthRequired,
	PreconditionFailed,
	RequestEntityTooLarge,
	RequestUriTooLong,
	UnsupportedMediaType,
	RequestedRangeNotSatisfiable,
	ExpectationFailed,
	UpgradeRequired,
	InternalServerError,
	NotImplemented,
	BadGateway,
	ServiceUnavailable,
	GatewayTimeout,
	HttpVersionNotSupported,
	;

}
